//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChartOfAccount
    {
        public int AccountId { get; set; }
        public string AccountGroupCode { get; set; }
        public string Description { get; set; }
        public string Classification { get; set; }
        public string GroupType { get; set; }
        public string Status { get; set; }
        public string GLCode { get; set; }
        public string Branch { get; set; }
        public string Department { get; set; }
        public string Currency { get; set; }
        public bool ICAccount { get; set; }
        public bool ControlAccount { get; set; }
        public bool BankAccount { get; set; }
        public string DefaultTaxCode { get; set; }
        public string ReceivableInvoiceType { get; set; }
        public string ReceivableCreditNoteType { get; set; }
        public string ReceivableReceiptType { get; set; }
        public string PayableBillType { get; set; }
        public string PayableDebitNoteType { get; set; }
        public string PayablePaymentType { get; set; }
        public string JournalType { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    }
}
