//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Transactions = new HashSet<Transaction>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string TaxNumber { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public DateTime FiscalYearStart { get; set; }
        public DateTime FiscalYearEnd { get; set; }
        public string LogoUrl { get; set; }
        public string Industry { get; set; }
        public string Status { get; set; }
        public string Website { get; set; }
        public string ContactPerson { get; set; }
        public string Telephone { get; set; }
        public string PrimaryEmail { get; set; }
        public string PAN { get; set; }
        public string VAT { get; set; }
        public string TimeZone { get; set; }
        public string Language { get; set; }
        public int? LanguageId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string Zipcode { get; set; }
        public string Country { get; set; }
        public int? Contry_Id { get; set; }
        public string State { get; set; }
        public int? State_Id { get; set; }
        public string DefaultCurrency { get; set; }
        public int? Currency_Id { get; set; }
        public string City { get; set; }
        public int? City_Id { get; set; }
        public string AccountingBasis { get; set; }
        public int? Accounting_Id { get; set; }
        public int? Entity_Id { get; set; }
        public int? Login_Id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaction> Transactions { get; set; }
    }
}
