//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Core_Currency
    {
        public int CoreCurncy_ID { get; set; }
        public string CoreCurncy_Code { get; set; }
        public string CoreCurncy_Desc { get; set; }
        public string CoreCurncy_Major { get; set; }
        public string CoreCurncy_Minor { get; set; }
        public string CoreCurncy_Symbol { get; set; }
        public string CoreCurncy_Seperator { get; set; }
        public string CoreCurncy_Format { get; set; }
        public Nullable<int> CoreCurncy_Decimal { get; set; }
    }
}
