//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public Nullable<decimal> AmountOutstanding { get; set; }
        public Nullable<decimal> UnusedCredit { get; set; }
        public int StatusId { get; set; }
        public string Code { get; set; }
        public string Website { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string Department { get; set; }
        public string DefaultCurrency { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string CorrespondenceAddress1 { get; set; }
        public string CorrespondenceAddress2 { get; set; }
        public string City2 { get; set; }
        public string State2 { get; set; }
        public string Country2 { get; set; }
        public string ZipCode { get; set; }
        public string ZipCode2 { get; set; }
        public string BankCurrency { get; set; }
        public string AccountNumber { get; set; }
        public string Payee { get; set; }
        public string BankName { get; set; }
        public string IBAN_IFSC { get; set; }
        public string SWIFTCode { get; set; }
        public string SORTCode { get; set; }
        public Nullable<bool> IsDefaultBank { get; set; }
        public string GST_VAT { get; set; }
        public string PAN { get; set; }
        public string TaxCode { get; set; }
        public Nullable<decimal> BillPercentage { get; set; }
        public string DueDateBasedOn { get; set; }
        public Nullable<int> CreditDays { get; set; }
        public Nullable<decimal> CreditLimits { get; set; }
    
        public virtual CustomerStatu CustomerStatu { get; set; }
    }
}
