//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Partner
    {
        public long Partner_Id { get; set; }
        public string Partner_Code { get; set; }
        public string Partner_Name { get; set; }
        public string Partner_Status { get; set; }
        public int Partner_TaxID { get; set; }
        public long Partner_ParentID { get; set; }
        public bool Is_Parent { get; set; }
        public int Partner_CityID { get; set; }
        public int Partner_LamarkID { get; set; }
        public int Partner_CurrencyID { get; set; }
        public bool Partner_net { get; set; }
        public string Partner_Login { get; set; }
        public string Partner_Password { get; set; }
        public string Partner_PANURL { get; set; }
        public string Partner_TANURL { get; set; }
        public string Partner_VATURL { get; set; }
        public string Partner_PAN { get; set; }
        public string Partner_TAN { get; set; }
        public string Partner_VAT { get; set; }
        public Nullable<int> Partner_ClassID { get; set; }
        public Nullable<int> Partner_Priority { get; set; }
        public string LatLong { get; set; }
        public string Partner_FSheet { get; set; }
        public string Partner_HSaftey { get; set; }
        public string Partner_Url { get; set; }
        public string Partner_Logo { get; set; }
        public string Partner_RegNumber { get; set; }
        public string Partner_IntCode { get; set; }
        public Nullable<bool> Partner_InStock { get; set; }
        public int Flex1_ID { get; set; }
        public int Flex2_ID { get; set; }
        public int Flex3_ID { get; set; }
        public int Flex4_ID { get; set; }
        public int Flex5_ID { get; set; }
        public int Flex6_ID { get; set; }
        public int Flex7_ID { get; set; }
        public int Flex8_ID { get; set; }
        public int Flex9_ID { get; set; }
        public int Flex10_ID { get; set; }
        public bool I_Block { get; set; }
        public bool D_Block { get; set; }
        public bool P_Block { get; set; }
        public string Description { get; set; }
        public string Partner_Expedia { get; set; }
        public string Partner_ImgUrl1 { get; set; }
        public string Partner_ImgUrl2 { get; set; }
        public string Partner_Airport { get; set; }
        public int Partner_Confidance { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] timestamp { get; set; }
        public bool Partner_IsOnline { get; set; }
        public int Partner_StarCat { get; set; }
        public string Partner_FSafety { get; set; }
        public bool Partner_IsAdhoc { get; set; }
        public string PartnerTheme_ID { get; set; }
        public string Partner_Mobile { get; set; }
        public string Partner_Title { get; set; }
        public string Partner_FName { get; set; }
        public string Partner_LName { get; set; }
        public string ContentLanguage { get; set; }
        public Nullable<System.DateTime> Partner_PasswordExpiry { get; set; }
        public Nullable<int> Partner_LCount { get; set; }
    }
}
