//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_ExchangeRate
    {
        public int Exrate_ID { get; set; }
        public int Exrate_SourceID { get; set; }
        public int Exrate_TargetID { get; set; }
        public int Exrate_ExTypeID { get; set; }
        public decimal Exrate_ExRate { get; set; }
        public System.DateTime Exrate_ExDate { get; set; }
        public string Exrate_ExFactor { get; set; }
        public int Exrate_Priority { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual mst_Currency mst_Currency { get; set; }
        public virtual mst_Currency mst_Currency1 { get; set; }
        public virtual mst_Entity mst_Entity { get; set; }
        public virtual mst_ExchangeType mst_ExchangeType { get; set; }
    }
}
