//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Exception
    {
        public long Excep_ID { get; set; }
        public string ProcessName { get; set; }
        public Nullable<int> Excep_Code { get; set; }
        public string Excep_Desc { get; set; }
        public Nullable<int> Excep_At { get; set; }
        public System.DateTime ProcessDate { get; set; }
        public int ProcessBy { get; set; }
        public int Entity_ID { get; set; }
    }
}
