//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_City
    {
        public int City_ID { get; set; }
        public string City_Code { get; set; }
        public string City_Desc { get; set; }
        public int City_StateID { get; set; }
        public int City_CountryID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] timestamp { get; set; }
        public string City_ShortDesc { get; set; }
        public string City_LongDesc { get; set; }
        public string City_Image { get; set; }
        public string City_Theme { get; set; }
        public string City_BestBuy { get; set; }
        public string City_Attraction { get; set; }
        public string City_Food { get; set; }
        public string City_Activity { get; set; }
        public string City_Lat { get; set; }
        public string City_Long { get; set; }
        public int City_ProvinceID { get; set; }
        public bool City_ShowOnGUI { get; set; }
    
        public virtual mst_Country mst_Country { get; set; }
        public virtual mst_Entity mst_Entity { get; set; }
        public virtual mst_State mst_State { get; set; }
    }
}
