//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Division
    {
        public int Div_ID { get; set; }
        public string Div_Code { get; set; }
        public string Div_Desc { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public string Div_BookEmail { get; set; }
    }
}
