//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Entity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_Entity()
        {
            this.mst_BedType = new HashSet<mst_BedType>();
            this.mst_City = new HashSet<mst_City>();
            this.mst_Country = new HashSet<mst_Country>();
            this.mst_Currency = new HashSet<mst_Currency>();
            this.mst_ExchangeRate = new HashSet<mst_ExchangeRate>();
            this.mst_ExchangeType = new HashSet<mst_ExchangeType>();
            this.mst_Market = new HashSet<mst_Market>();
            this.mst_Rate = new HashSet<mst_Rate>();
            this.mst_Region = new HashSet<mst_Region>();
            this.mst_ServiceType = new HashSet<mst_ServiceType>();
            this.mst_TaxMapping = new HashSet<mst_TaxMapping>();
            this.trn_Configuration = new HashSet<trn_Configuration>();
            this.trn_Configuration1 = new HashSet<trn_Configuration>();
            this.trn_Rate = new HashSet<trn_Rate>();
            this.trn_ServiceConfig = new HashSet<trn_ServiceConfig>();
            this.trn_Tax = new HashSet<trn_Tax>();
        }
    
        public int Entity_ID { get; set; }
        public string Entity_Code { get; set; }
        public string Entity_Desc { get; set; }
        public int Entity_CountryID { get; set; }
        public decimal Entity_TimeZone { get; set; }
        public string Entity_Logo { get; set; }
        public string Entity_Spoc { get; set; }
        public int Entity_MasterID { get; set; }
        public string Entity_Address1 { get; set; }
        public string Entity_Address2 { get; set; }
        public int Entity_CityID { get; set; }
        public int Entity_StateID { get; set; }
        public string Entity_Phone { get; set; }
        public string Entity_Fax { get; set; }
        public string Entity_Web { get; set; }
        public string Entity_Pan { get; set; }
        public string Entity_Tan { get; set; }
        public string Entity_Zip { get; set; }
        public int Max_User { get; set; }
        public string Entity_Ver { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public byte[] timestamp { get; set; }
        public byte[] Entity_Report_logo1 { get; set; }
        public byte[] Entity_Report_logo2 { get; set; }
        public string Entity_ReportAddress1 { get; set; }
        public string Entity_ReportAddress2 { get; set; }
        public string Entity_Report_logoName1 { get; set; }
        public string Entity_Report_logoName2 { get; set; }
        public int Entity_OCCount { get; set; }
        public bool Entity_Publisher { get; set; }
        public bool Entity_Subscriber { get; set; }
        public bool Entity_2FARequired { get; set; }
        public Nullable<System.DateTime> Entity_2FAEnforce { get; set; }
        public string Entity_IPAddress { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_BedType> mst_BedType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_City> mst_City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_Country> mst_Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_Currency> mst_Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_ExchangeRate> mst_ExchangeRate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_ExchangeType> mst_ExchangeType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_Market> mst_Market { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_Rate> mst_Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_Region> mst_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_ServiceType> mst_ServiceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_TaxMapping> mst_TaxMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_Configuration> trn_Configuration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_Configuration> trn_Configuration1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_Rate> trn_Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_ServiceConfig> trn_ServiceConfig { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_Tax> trn_Tax { get; set; }
    }
}
