//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_Services()
        {
            this.trn_Rate = new HashSet<trn_Rate>();
            this.trn_ServiceConfig = new HashSet<trn_ServiceConfig>();
        }
    
        public long Service_Id { get; set; }
        public long Service_RoomID { get; set; }
        public long Service_ViewID { get; set; }
        public int Service_SrvTypID { get; set; }
        public int Service_CityID { get; set; }
        public int Service_LamarkID { get; set; }
        public long Service_PartnerID { get; set; }
        public string Service_Name { get; set; }
        public string Service_ConfigType { get; set; }
        public string Service_ChargeOn { get; set; }
        public string Service_ChargeBy { get; set; }
        public int Service_Inventory { get; set; }
        public string Service_Size { get; set; }
        public int Service_MaxChargeon { get; set; }
        public int Service_Priority { get; set; }
        public string Service_Slot { get; set; }
        public int Service_Period { get; set; }
        public int Service_ADFrom { get; set; }
        public int Service_ADTo { get; set; }
        public int Service_TEFrom { get; set; }
        public int Service_TETo { get; set; }
        public int Service_CHFrom { get; set; }
        public int Service_CHTo { get; set; }
        public int Service_INFrom { get; set; }
        public int Service_INTo { get; set; }
        public long Flex1_ID { get; set; }
        public long Flex2_ID { get; set; }
        public long Flex3_ID { get; set; }
        public long Flex4_ID { get; set; }
        public long Flex5_ID { get; set; }
        public long Flex6_ID { get; set; }
        public long Flex7_ID { get; set; }
        public long Flex8_ID { get; set; }
        public long Flex9_ID { get; set; }
        public long Flex10_ID { get; set; }
        public string Service_Type { get; set; }
        public bool Service_IncTE { get; set; }
        public bool Service_IncCH { get; set; }
        public bool Service_IncIN { get; set; }
        public bool Service_Internet { get; set; }
        public int Service_Seq { get; set; }
        public bool Service_SIC { get; set; }
        public string Service_SICName { get; set; }
        public bool Service_HeightPolicy { get; set; }
        public string Service_EANRoomID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] timestamp { get; set; }
        public bool Service_ICR { get; set; }
        public bool Service_ICRSelf { get; set; }
        public string Service_Amenties { get; set; }
        public int Service_ICRCount { get; set; }
        public long Service_ICRServID { get; set; }
        public bool Service_SubSrv { get; set; }
        public bool Service_SubSrvHdr { get; set; }
        public string Service_SubSrvName { get; set; }
        public int Service_SubSrvLangID { get; set; }
        public string Service_SubSrvTime { get; set; }
        public int Service_SubVechID { get; set; }
        public string Service_SubSrvDur { get; set; }
        public long Service_SubSrvID { get; set; }
        public string Service_Detail { get; set; }
        public int Service_HF { get; set; }
        public int Service_HT { get; set; }
        public bool Service_IsAdhoc { get; set; }
        public string Service_Lat { get; set; }
        public string Service_Long { get; set; }
        public string Service_Mrkuptype { get; set; }
        public decimal Service_MrkupVal { get; set; }
        public int Service_RowNo { get; set; }
        public decimal Service_MrkupValCh { get; set; }
        public Nullable<long> Service_MainID { get; set; }
        public int Service_DocID { get; set; }
        public string Service_DocType { get; set; }
        public string PriorityType { get; set; }
        public string DocumentType { get; set; }
        public int Service_BarCodeID { get; set; }
        public bool Service_B2C { get; set; }
        public Nullable<int> Service_SubSrvlug { get; set; }
        public string Service_SubSrvToTime { get; set; }
        public Nullable<int> ProductCatId { get; set; }
        public string ContentLanguage { get; set; }
        public Nullable<bool> Service_Pinned { get; set; }
        public Nullable<int> Service_PPriority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_Rate> trn_Rate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_ServiceConfig> trn_ServiceConfig { get; set; }
    }
}
