//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_GLMaster
    {
        public long GL_ID { get; set; }
        public string GL_Code { get; set; }
        public string GL_Desc { get; set; }
        public string GL_Class { get; set; }
        public int GL_BranchID { get; set; }
        public int GL_DeptmtID { get; set; }
        public string GL_Display { get; set; }
        public bool GL_Control { get; set; }
        public bool GL_IC { get; set; }
        public bool GL_IMD { get; set; }
        public string GL_R_Invoice { get; set; }
        public string GL_R_Credit { get; set; }
        public string GL_R_Reciept { get; set; }
        public string GL_P_Invoice { get; set; }
        public string GL_P_Debit { get; set; }
        public string GL_P_Payment { get; set; }
        public string GL_G_Posting { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public bool GL_Bank { get; set; }
        public long GL_GLGrpID { get; set; }
    }
}
