//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Branch
    {
        public int Branch_ID { get; set; }
        public string Branch_Code { get; set; }
        public string Branch_Desc { get; set; }
        public Nullable<int> Branch_CityId { get; set; }
        public bool Branch_Private { get; set; }
        public bool Branch_Group { get; set; }
        public string GSTNO { get; set; }
        public string Branch_Address1 { get; set; }
        public string Branch_Address2 { get; set; }
        public string Branch_Address3 { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public Nullable<int> ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] timestamp { get; set; }
        public int Branch_DivID { get; set; }
    }
}
