//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;

    public class mst_Tax
    {
        public int Tax_ID { get; set; }
        public string Tax_Code { get; set; }
        public string Tax_Desc { get; set; }
        public string Tax_factor { get; set; }
        public string Tax_Value { get; set; }
        public int Tax_appliedon { get; set; }
        public long? Tax_GLIN { get; set; }
        public long? Tax_GLOUT { get; set; }
        public bool Is_InterState { get; set; }
        public DateTime CreateDate { get; set; }
        public bool Active { get; set; }
        public bool Isgroup { get; set; }
        public int Entity_ID { get; set; }
        public int Login_ID { get; set; }
        public byte[] timestamp { get; set; }
        public bool Tax_Include { get; set; }
        public int Tax_Seq { get; set; }
        public string Tax_type { get; set; }
        public bool Tax_WithHold { get; set; }
        public int Records { get; set; }
        public int ComputationBasis { get; set; }

        public string CertificateNo { get; set; }
        public string EffectiveFrom { get; set; }
        // TDS-specific fields
        public string TDS_Section { get; set; }
        public decimal? Threshold_Limit { get; set; }
        public decimal? EffectiveAmount { get; set; }
        public string LTDC_EffectiveDate { get; set; }
        public string TDS_EffectiveDate { get; set; }
        public int TdsType { get; set; }
        public int? LedgerAccount { get; set; }

        // Runtime-only tag: "GST" | "TDS" | "OTHER"
        public string TaxCategory { get; set; }
    }

    public class TaxDetail
    {
        public string AssociatedTax { get; set; }
        public string TaxRate { get; set; }
        public string TaxAccount { get; set; }
        public string TaxAccountCreditNote { get; set; }
    }
}
