//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_Rate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_Rate()
        {
            this.trn_Rate = new HashSet<trn_Rate>();
        }
    
        public long Rate_Id { get; set; }
        public string Rate_Name { get; set; }
        public int Rate_MarketID { get; set; }
        public long Rate_PartnerID { get; set; }
        public string Rate_Status { get; set; }
        public string Rate_BookBeforeType { get; set; }
        public int Rate_BookBefore { get; set; }
        public string Rate_Tax { get; set; }
        public int Rate_CurrencyID { get; set; }
        public System.TimeSpan Rate_CheckIn { get; set; }
        public System.TimeSpan Rate_CheckOut { get; set; }
        public int Rate_GroupFrom { get; set; }
        public bool Rate_SmMon { get; set; }
        public bool Rate_SmTue { get; set; }
        public bool Rate_SmWed { get; set; }
        public bool Rate_SmThu { get; set; }
        public bool Rate_SmFri { get; set; }
        public bool Rate_SmSat { get; set; }
        public bool Rate_SmSun { get; set; }
        public bool Rate_SiMon { get; set; }
        public bool Rate_SiTue { get; set; }
        public bool Rate_SiWed { get; set; }
        public bool Rate_SiThu { get; set; }
        public bool Rate_SiFri { get; set; }
        public bool Rate_SiSat { get; set; }
        public bool Rate_SiSun { get; set; }
        public int Rate_BaseMealID { get; set; }
        public System.TimeSpan Rate_Maxhour { get; set; }
        public string Rate_RateFor { get; set; }
        public bool Rate_Commision { get; set; }
        public string Rate_CommType { get; set; }
        public decimal Rate_CommVal { get; set; }
        public string Rate_CommDue { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] timestamp { get; set; }
        public bool Rate_ChildFree { get; set; }
        public int Rate_FreeTill { get; set; }
        public bool Rate_MultiChild { get; set; }
        public string Rate_Code { get; set; }
        public decimal Rate_FreeAgeF { get; set; }
        public decimal Rate_FreeAgeT { get; set; }
        public int Rate_SglMulti { get; set; }
        public int Rate_Priority { get; set; }
        public System.DateTime Rate_SaleFrom { get; set; }
        public System.DateTime Rate_SaleTo { get; set; }
        public bool Rate_Special { get; set; }
        public long Rate_SourceID { get; set; }
        public bool Rate_CommWithTax { get; set; }
        public bool Rate_IsMealExcluded { get; set; }
        public decimal Rate_MealPrice { get; set; }
        public bool Rate_IsEBIncluded { get; set; }
    
        public virtual mst_Entity mst_Entity { get; set; }
        public virtual mst_Market mst_Market { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trn_Rate> trn_Rate { get; set; }
    }
}
