//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_BedType
    {
        public int Bed_ID { get; set; }
        public string Bed_Code { get; set; }
        public string Bed_Desc { get; set; }
        public int Bed_Adult { get; set; }
        public int Bed_Teen { get; set; }
        public int Bed_Child { get; set; }
        public int Bed_Infant { get; set; }
        public int Bed_Total { get; set; }
        public bool Bed_ExBed { get; set; }
        public bool Bed_Rollover { get; set; }
        public bool Bed_AdChk { get; set; }
        public int Bed_Multiple { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual mst_Entity mst_Entity { get; set; }
    }
}
