//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class mst_ServiceType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mst_ServiceType()
        {
            this.mst_TaxMapping = new HashSet<mst_TaxMapping>();
        }
    
        public int SrvTyp_ID { get; set; }
        public string SrvTyp_Code { get; set; }
        public string SrvTyp_Desc { get; set; }
        public string SrvTyp_Type { get; set; }
        public bool SrvTyp_Acc { get; set; }
        public bool SrvTyp_Apt { get; set; }
        public bool SrvTyp_Pkg { get; set; }
        public bool SrvTyp_Nac { get; set; }
        public string SrvTyp_Display { get; set; }
        public string SrvTyp_Icon { get; set; }
        public long SrvTyp_ARControl { get; set; }
        public long SrvTyp_APControl { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] timestamp { get; set; }
        public int SrvTyp_SACCode { get; set; }
        public bool SrvType_SCPP { get; set; }
        public bool Srvtyp_isCT { get; set; }
        public string SubSrvTyp_Type { get; set; }
    
        public virtual mst_Entity mst_Entity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mst_TaxMapping> mst_TaxMapping { get; set; }
    }
}
