//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class mst_Currency
    {
        public List<CurrencyList> CurrencyList { get; set; }
        public List<CurrencyExchangeRate> ExchangeRate { get; set; }
    }

    public class CurrencyList
    {
        public int Curncy_ID { get; set; }
        public string Curncy_Code { get; set; }
        public string Curncy_Desc { get; set; }
        public string Curncy_Major { get; set; }
        public string Curncy_Minor { get; set; }
        public string Curncy_Symbol { get; set; }
        public string Curncy_Seperator { get; set; }
        public string Curncy_Format { get; set; }
        public int Curncy_Decimal { get; set; }
        public bool Active { get; set; }
        public byte[] timestamp { get; set; }
        public int TotalRecord { get; set; }
    }

    public class CurrencyExchangeRate
    {
        public int ID { get; set; }
        public string FromCurrency { get; set; }
        public string ToCurrency { get; set; }
        public string RateType { get; set; }
        public DateTime EffectiveDate { get; set; }
        public string MultDiv { get; set; }
        public decimal ExchangeRate { get; set; }
        public decimal RateReciprocal { get; set; }
        public string CurrencyUnitEquivalents { get; set; }
        public int TotalRecord { get; set; }
    }

    public class ExchangeRateViewModel
    {
        public int FromCurrencyId { get; set; }
        public int ToCurrencyId { get; set; }
        public int CurrencyRateTypeId { get; set; }
        public string EffectivefromDate { get; set; }
        public string EffectivetoDate { get; set; }
        public decimal CurrencyRate { get; set; }
        public string MultDiv { get; set; }  // "Multiply" or "Divide"
        public int? Entity_ID { get; set; }
        public int? Login_ID { get; set; }
    }

    public class ApiResponse
    {
        public bool Success { get; set; }
        public string Message { get; set; }
        public object Data { get; set; }
    }

    public class CurrencyRateType
    {
        public int RateTypeId { get; set; }

        [Required(ErrorMessage = "Rate Type Code is required")]
        [StringLength(50)]
        public string RateTypeCode { get; set; }

        [Required(ErrorMessage = "Description is required")]
        [StringLength(200)]
        public string Description { get; set; }

        public bool RefreshOnline { get; set; }

        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? Entity_ID { get; set; }
        public int? Login_ID { get; set; }
    }
}
