//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpeningBalanceDetail
    {
        public int Id { get; set; }
        public int OpeningBalanceId { get; set; }
        public string Type { get; set; }
        public System.DateTime Date { get; set; }
        public string CustomerOrVendor { get; set; }
        public string Currency { get; set; }
        public string Reference { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<int> CustomerId { get; set; }
    
        public virtual OpeningBalance OpeningBalance { get; set; }
    }
}
