//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_Configuration
    {
        public int Tconfg_ID { get; set; }
        public string Tconfg_Name { get; set; }
        public string Tconfg_Module { get; set; }
        public string Tconfg_Value { get; set; }
        public int Tconfg_UserId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] timestamp { get; set; }
    
        public virtual mst_Entity mst_Entity { get; set; }
        public virtual mst_Entity mst_Entity1 { get; set; }
    }
}
