//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_Rate
    {
        public long TR_Rate_ID { get; set; }
        public long TR_RateID { get; set; }
        public long TR_ServiceID { get; set; }
        public long TR_TSCServiceID { get; set; }
        public int TSC_BedID { get; set; }
        public System.DateTime TR_FromDate { get; set; }
        public System.DateTime TR_ToDate { get; set; }
        public bool TR_Mon { get; set; }
        public bool TR_Tue { get; set; }
        public bool TR_Wed { get; set; }
        public bool TR_Thu { get; set; }
        public bool TR_Fri { get; set; }
        public bool TR_Sat { get; set; }
        public bool TR_Sun { get; set; }
        public int TR_Min { get; set; }
        public int TR_Max { get; set; }
        public int TR_FZoneID { get; set; }
        public int TR_TZoneID { get; set; }
        public decimal TR_Cost { get; set; }
        public decimal TR_Sell { get; set; }
        public string ValidDays { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public decimal TR_SrvTax { get; set; }
        public decimal TR_TaxPer { get; set; }
        public string TR_TaxType { get; set; }
        public decimal TR_CommValue { get; set; }
        public string TR_MarkupType { get; set; }
        public Nullable<decimal> TR_MarkupValue { get; set; }
    
        public virtual mst_Entity mst_Entity { get; set; }
        public virtual mst_Rate mst_Rate { get; set; }
        public virtual mst_Services mst_Services { get; set; }
    }
}
