//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fintech
{
    using System;
    using System.Collections.Generic;
    
    public partial class trn_ServiceConfig
    {
        public long TSC_Service_ID { get; set; }
        public long TSC_ServiceID { get; set; }
        public string TSC_Type { get; set; }
        public int TSC_BedID { get; set; }
        public int TSC_Adult { get; set; }
        public int TSC_Teen { get; set; }
        public int TSC_Child { get; set; }
        public int TSC_Infant { get; set; }
        public int TSC_Total { get; set; }
        public bool TSC_ExBed { get; set; }
        public bool TSC_Rollover { get; set; }
        public bool TSC_AdChk { get; set; }
        public int TSC_FromPax { get; set; }
        public int TSC_ToPax { get; set; }
        public int TSC_Multiple { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime ChangeDate { get; set; }
        public int ChangeBy { get; set; }
        public bool Active { get; set; }
        public int Entity_ID { get; set; }
        public byte[] Timestamp { get; set; }
    
        public virtual mst_Entity mst_Entity { get; set; }
        public virtual mst_Services mst_Services { get; set; }
    }
}
